### PR TITLE
CI: Add SBOM Generation and Update E2E Tests

### PR DESCRIPTION
**Pull request by alegrey91**
## PR Type:
Enhancement

___
## PR Description:
This PR introduces the generation of Software Bill of Materials (SBOM) for the Docker image as part of the CI process. It also updates the end-to-end tests workflow and adds a section in the README about SBOM verification.

___
## PR Main Files Walkthrough:
-`.github/workflows/build.yaml`: Added a new step in the CI process to generate SBOM for the Docker image using the anchore/sbom-action.
-`.github/workflows/e2e-tests.yaml`: Updated the workflow to use a different GitHub token and added an environment variable for the GitHub token.
-`README.md`: Added a new section about SBOM verification, recommending the use of grype for vulnerability scanning.

### CODE REVIEW

**Review by yuleib — APPROVED** [review]

**Comment by dwertent** [comment]
/improve --text="if this is a PR with s

**Pull request closed without merging**
